[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.27"

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "${CHAIN_RPC_ENDPOINT}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
